### ISSUE TITLE
Station Name issue

### ISSUE THREAD

**Issue by mineshmshah** [FAC-11/week3-TAAA#34] opened 2017-07-14 09:20 UTC
When loading result the bullet points all show station name and is not cycling giving the relevant station name. So for example when you search for bank station it could be like the following:

- Station name : Bank station

It just makes it easier to see what station it refers rather than having to look in the youtube link :)

**Comment by absorpheus** [comment] 2017-07-14 09:46
Duplicate of issue #22

**Closed as completed by absorpheus** 2017-07-14 09:46 UTC
